apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-config
  namespace: {{ .Values.app.namespace }}
data:
  index.html: |
   <!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Cloud With VarJosh</title>

  <style>
    body {
      margin: 0;
      padding: 0;
      height: 100vh;
      display: flex;
      justify-content: center;
      align-items: center;
      background: linear-gradient(135deg, #0f172a, #1e40af, #2563eb);
      font-family: Arial, sans-serif;
      color: white;
      overflow: hidden;
    }

    .container {
      text-align: center;
      background: rgba(255, 255, 255, 0.08);
      padding: 40px;
      border-radius: 16px;
      backdrop-filter: blur(6px);
      box-shadow: 0 8px 25px rgba(0,0,0,0.3);
      width: 80%;
      max-width: 700px;
    }

    h1 {
      font-size: 42px;
      margin-bottom: 15px;
    }

    .highlight {
      color: #38bdf8;
    }

    p {
      font-size: 18px;
      color: #dbeafe;
      margin-bottom: 30px;
    }

    .badges {
      margin-top: 20px;
    }

    .badge {
      display: inline-block;
      margin: 8px;
      padding: 10px 18px;
      border-radius: 30px;
      background: rgba(255,255,255,0.15);
      border: 1px solid rgba(255,255,255,0.2);
      font-size: 14px;
    }

    .footer {
      margin-top: 30px;
      font-size: 14px;
      color: #cbd5e1;
    }
  </style>
</head>

<body>

  <div class="container">
    <h1>🚀 Practice with <span class="highlight">ArgoCD and Helm</span></h1>

    <div class="badges">
      <span class="badge">☸ Kubernetes</span>
      <span class="badge">🚀 ArgoCD</span>
      <span class="badge">📦 Helm</span>
    </div>

    <div class="footer">
      GitOps Powered Deployment using ArgoCD + Helm
    </div>
  </div>

</body>
</html>